### PR TITLE
Suggestion of new structure.

### PR DESCRIPTION
**Pull request by pauloiankoski**
Suggestion of a new structure very similar to WooCommerce

### CODE REVIEW

**Comment by msaggiorato** [comment]
Minified files seems unnecesary. This should be "gulpified" and automatically minified if needed. Same for SASS support on plugins.

What do you think @pauloiankoski ?

**Comment by pauloiankoski** [comment]
Yeah. I'd not spend time for gulp yet until have your approve for this new
structure. But my idea is to have a files minified by Gulp and SASS support.

Paulo Iankoski
(51) 99977.4220

2017-06-05 18:15 GMT-03:00 Matias Saggiorato <notifications@github.com>:

**Comment by msaggiorato** [comment]
Shouldn't customizations be autoloaded aswell? The files themselves i mean.

You could just then do:

`
$this->acf = new PName_ACF_Customizations();
`

Or something on those lines on the main plugin file. Not sure if it would be a good approach tho.

**Comment by pauloiankoski** [comment]
Autoload works along with class initialization. I thought the simplest way to load classes so you only need to include plugin/theme name being customized in that array.

About `$this->acf` I don't agree of having these classes as public. All classes inside customizations folder must have only pairs of hooks + functions. So there's no reasons for having those as public.

About your last sentence, that's not a surprise for me ;)

**Comment by msaggiorato** [comment]
> About your last sentence, that's not a surprise for me ;)

Not sure what you mean.

**Pull request merged**
